on: [push]

jobs:
  List-Branches:
    runs-on: ubuntu-latest
    name: Job para listar Branches de reposit√≥rio GitHub
    steps:
      - name: Listar Branches action step
        id: list
        uses: geovanams/list-branchs-action@v3
        with:
          owner: 'geovanams'
          repos: 'list-branchs-action'
